# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4903ac48fcc735b84d3dd7f4c200fe54621092e4526796be402bc5a2f2d0e2b5b9d61589817a7ae20df570b989add9e6288683e6d9adae9d91d90abe2d29e07c

test:
  secret_key_base: 102ebbbb6a01ba2432f633b6cae29241ea27ca1e87715862eab3d039d6785d627ef75dbf7ff3f40714ba2f0d0817691c456d071ddadcd0b5e48d959f994824cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
